# F3V3R DR34M KEYGEN STYLE WORKFLOW
# MAXIMUM CROSS-PLATFORM DEPLOYMENT PROTOCOL
# WINDOWS + LINUX COMPATIBILITY: ACTIVATED

name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug Directory Structure
        run: |
          echo " F3V3R DR34M FILE CHECK PROTOCOL "
          pwd
          ls -la
          echo "Total files:"
          find . -type f | wc -l

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Create Artifact Directory
        run: |
          echo " CREATING DEPLOYMENT PACKAGE "
          mkdir _site
          cp -r * .nojekyll _site/ 2>/dev/null || :
          ls -la _site/

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_site"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
